### ISSUE TITLE
Gradle sync fails in version 3.2.0

### ISSUE THREAD

**Issue by mateot1** [Eppo-exp/android-sdk#78]
3.1.0 fails with unresolved references, which I see had this attempted fix: https://github.com/Eppo-exp/android-sdk/pull/71, but 3.2.0 fails with:
```
Could not find cloud.eppo:sdk-common-jvm:2.0.0-SNAPSHOT.
Required by:
    project :app > cloud.eppo:android-sdk:3.2.0
```

**Comment by felipecsl** [comment]
@mateot1 we recently updated the README instructions on #78 to address that. let us know if that solves it for you

**Comment by felipecsl** [comment]
For the next version we'll no longer be using `cloud.eppo:sdk-common-jvm:2.0.0-SNAPSHOT`, so if you want to just wait for the next version, then this workaround shouldn't be needed anymore

**Comment by mateot1** [comment]
@felipecsl yep, adding the maven url fixes it, thank you.
